server:
  port: "8001"


spring:
  cloud:
    config:
      server:
        git:
          uri: "git@bitbucket.org:alokailawadi/configdata.git"
      label: master
      fail-fast: true

  application:
    name: config-service
